# if you use github, you should move this file to .github/workflows
name: github-ci
on:
  push:
    branches:
      - main
      - test
jobs:

  CIManager:
    runs-on: ubuntu-latest
    env:
      # define directory in gitHub action
      working-directory: .github/../

      # variable configuration for [check code]
      CHECK_CODE_SWITCH: "on"

      # variable configuration for [unit test]
      UNIT_TEST_SWITCH: "on"
      UNIT_TEST_TRIGGER_CMD: "cd tests && bash test.sh"
    steps:
      - uses: actions/checkout@v1
      - run: |
            printf "================ Start to Boot CIManager ================\n"
            git clone https://github.com/wgrape/CIManager.git
            cp -an ./CIManager/.pipeline ./
            rm -rf ./CIManager
            cd .pipeline
            printf "================ Boot CIManager Stopped ================\n\n"
            bash start.sh
