# if you use github, you should move this file to .github/workflows
name: github-ci
on:
  push:
    branches:
      - main
      - test
jobs:

  CIManager:
    runs-on: ubuntu-latest
    env:
      # define directory in gitHub action
      working-directory: .github/../

      # variable configuration for [check code]
      CHECK_CODE_SWITCH: "on"

      # variable configuration for [unit test]
      UNIT_TEST_SWITCH: "on"
      UNIT_TEST_TRIGGER_CMD: "cd tests && bash test.sh"
    steps:
      - uses: actions/checkout@v1
      - run: |
            printf "\033[32m================ Start to Boot CIManager ================\033[0m\n"
            git clone https://github.com/wgrape/CIManager.git
            cp -an ./CIManager/.pipeline ./
            rm -rf ./CIManager
            cd .pipeline
            printf "\033[32m================ End Boot ================\033[0m\n\n"
            printf "\033[32m================ Debug Start ================\033[0m\n\n"
            show_env(){
                echo "1. cat /proc/version="$(cat /proc/version)
                echo "2. CI_BUILDS_DIR=${CI_BUILDS_DIR}"
                echo "3. pwd="$(pwd)
                echo "4. ls="$(ls -a)
            }
            show_env
            printf "\033[32m================ End Debug ================\033[0m\n\n"
            printf "\033[32m>>>>>>>>>>> Start Pipeline\033[0m\n\n"
            bash start.sh
            printf "\n\n\033[32m<<<<<<<<<<< End Pipeline\033[0m"
