name: CICD
on:
  push:
    branches:
      - main

jobs:
  CIManager:
    runs-on: ubuntu-latest
    env:
      # ========================= CI =========================
      # [stage] = pre
      CI_STAGE_PRE_JOB_PRE_CHECK_SWITCH: "ON"
      CI_STAGE_PRE_JOB_PRE_INSTALL_SWITCH: "ON"
      # [stage] = test
      CI_STAGE_TEST_JOB_UNIT_TEST_SWITCH: "ON"
      CI_STAGE_TEST_JOB_UNIT_TEST_TRIGGER_CMD: "cd tests && bash test.sh"
      CI_STAGE_TEST_JOB_CHECK_CODE_SWITCH: "ON"
      # [stage] = build
      CI_STAGE_BUILD_JOB_LOCAL_BUILD_SWITCH: "ON"
      CI_STAGE_BUILD_JOB_APIDOC_GEN_SWITCH: "ON"
      # ========================= CD =========================
      # [stage] = deploy
      CD_STAGE_DEPLOY_JOB_SSH_SWITCH: "ON"
      # [stage] = monitor
      CD_STAGE_MONITOR_JOB_API_TEST_SWITCH: "ON"
      CD_STAGE_MONITOR_JOB_HEALTH_CHECK_SWITCH: "ON"
    steps:
      - uses: actions/checkout@v1
      - run: |
            printf "\e[36m================ Start to Boot CIManager ================\e[0m\n"
            git clone https://github.com/wgrape/CIManager.git
            cp -an ./CIManager/.pipeline ./
            rm -rf ./CIManager
            cd .pipeline
            printf "\e[36m================ End Boot ================\e[0m\n\n"
            printf "\e[36m================ Debug Start ================\e[0m\n\n"
            show_env(){
                echo "1. cat /proc/version="$(cat /proc/version)
                echo "2. CI_BUILDS_DIR=${CI_BUILDS_DIR}"
                echo "3. pwd="$(pwd)
                echo "4. ls="$(ls -a)
            }
            show_env
            printf "\e[36m================ End Debug ================\e[0m\n\n"
            printf "\e[36m>>>>>>>>>>> Start Pipeline\e[0m\n\n"
            bash start.sh
            printf "\n\n\e[36m<<<<<<<<<<< End Pipeline\e[0m"
